version: "3.9"
services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=servant-login
      - POSTGRES_USER=servant-login
    ports:
      - 5432:5432
